#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def config():
---
sources:
  - crd
provider: #@ data.values.provider
namespaceOverride: external-dns
#@yaml/text-templated-strings
(@= data.values.provider @): #@ data.values.providerSettings
pdb:
  create: false
extraDeploy:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: external-dns
crd:
  create: true
policy: sync
txtPrefix: #@ data.values.clusterGroup
txtOwnerId: #@ data.values.clusterGroup
#@ end

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: external-dns-values
  namespace: default
stringData:
  values.yml: #@ yaml.encode(config())