apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: externaldns
  namespace: default
spec:
  defaultNamespace: unusable-namespace
  packageRef:
    refName: externaldns.tanzu.field
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: pkg-installs-sa
  values:
  - secretRef:
      name: external-dns-values