apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: tpk8s-dns-controller
spec:
  secretEnv:
  - name: TP_HOST
    secretKeyRef:
      name: tpk8s-dns-controller-secret
      key: TP_HOST
  - name: PROJECT_ID
    secretKeyRef:
      name: tpk8s-dns-controller-secret
      key: PROJECT_ID
  - name: SPACES
    secretKeyRef:
      name: tpk8s-dns-controller-secret
      key: SPACES
  - name: MANAGED_DOMAINS
    secretKeyRef:
      name: tpk8s-dns-controller-secret
      key: MANAGED_DOMAINS
  - name: DEPLOYMENT_SPACE
    secretKeyRef:
      name: tpk8s-dns-controller-secret
      key: DEPLOYMENT_SPACE
  - name: ORG_ID
    secretKeyRef:
      name: tpk8s-dns-controller-secret
      key: ORG_ID
  - name: TPSM
    secretKeyRef:
      name: tpk8s-dns-controller-secret
      key: TPSM
  - name: TPSM_USER
    secretKeyRef:
      name: tpk8s-dns-controller-secret
      key: TPSM_USER
  - name: TPSM_PASS
    secretKeyRef:
      name: tpk8s-dns-controller-secret
      key: TPSM_PASS
  contact:
    team: tanzu-solutions-engineering
  build:
    nonSecretEnv:
      - name: BP_CPYTHON_VERSION
        value: "3.12.*"
    buildpacks: {}
    path: ../../dns-controller/src
